language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update && sudo apt-get install zlib1g-dev libmxml-dev libfftw3-dev liblo-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest --output-on-failure
